### ISSUE TITLE
BUG: -s to download the Screenshot isn´t working

### ISSUE THREAD

**Issue by ToastyBanK3nobi** [pearcebergh/DCSLiveryManager#4]
Hey folks, just a short one... the -s parameter isn´t working because the programm can´t dissolve the url for the screenshots. I think it´s because it doesn´t build the url in the corrent pattern, see the errors below:

Failed Livery Installs:
3313074: Failed during download of screenshot /upload/iblock/687/Miniature_AGS_AGS10CII1.jpg: Invalid URL '/upload/iblock/687/Miniature_AGS_AGS10CII1.jpg': No scheme supplied. Perhaps you meant
https:///upload/iblock/687/Miniature_AGS_AGS10CII1.jpg?
3317517: Failed during download of screenshot /upload/iblock/762/1wxod4zglct9jejf75hupvx0icbwxs8t/s1.JPG: Invalid URL '/upload/iblock/762/1wxod4zglct9jejf75hupvx0icbwxs8t/s1.JPG': No scheme supplied. Perhaps
you meant https:///upload/iblock/762/1wxod4zglct9jejf75hupvx0icbwxs8t/s1.JPG?
3322729: Failed during download of screenshot /upload/iblock/f57/obnes569rske188av8b6f9vd4r7tc6wy/8285d1.jpg: Invalid URL '/upload/iblock/f57/obnes569rske188av8b6f9vd4r7tc6wy/8285d1.jpg': No scheme supplied.
Perhaps you meant https:///upload/iblock/f57/obnes569rske188av8b6f9vd4r7tc6wy/8285d1.jpg?
3325421: Failed during download of screenshot /upload/iblock/90c/mmb1n1jxlkvt3gymxwjq6pcef0gh5p8y/banner.png: Invalid URL '/upload/iblock/90c/mmb1n1jxlkvt3gymxwjq6pcef0gh5p8y/banner.png': No scheme supplied.
Perhaps you meant https:///upload/iblock/90c/mmb1n1jxlkvt3gymxwjq6pcef0gh5p8y/banner.png?
3325661: Failed during download of screenshot /upload/iblock/aed/mldqa5wsdjyi4lyto78o0lzhqd215c4c/A-10C2_JaboG38_36_and_81_001.jpg: Invalid URL
'/upload/iblock/aed/mldqa5wsdjyi4lyto78o0lzhqd215c4c/A-10C2_JaboG38_36_and_81_001.jpg': No scheme supplied. Perhaps you meant
https:///upload/iblock/aed/mldqa5wsdjyi4lyto78o0lzhqd215c4c/A-10C2_JaboG38_36_and_81_001.jpg?
3326687: Failed during download of screenshot /upload/iblock/83f/q8aaz9eoxdymzu93rnl2fp73lcz90jf9/Raider.jpg: Invalid URL '/upload/iblock/83f/q8aaz9eoxdymzu93rnl2fp73lcz90jf9/Raider.jpg': No scheme supplied.
Perhaps you meant https:///upload/iblock/83f/q8aaz9eoxdymzu93rnl2fp73lcz90jf9/Raider.jpg?
3329007: Failed during download of screenshot /upload/iblock/5ff/h59o026crckln2rxsoy41fwsd5d46t3b/A10UEG.jpg: Invalid URL '/upload/iblock/5ff/h59o026crckln2rxsoy41fwsd5d46t3b/A10UEG.jpg': No scheme supplied.
Perhaps you meant https:///upload/iblock/5ff/h59o026crckln2rxsoy41fwsd5d46t3b/A10UEG.jpg?
3332125: Failed during download of screenshot /upload/userfiles/0e3/ykgx1g8h8t0ind7eqgrf0puj9v13b91y/BayouBandits.jpg: Invalid URL '/upload/userfiles/0e3/ykgx1g8h8t0ind7eqgrf0puj9v13b91y/BayouBandits.jpg': No
scheme supplied. Perhaps you meant https:///upload/userfiles/0e3/ykgx1g8h8t0ind7eqgrf0puj9v13b91y/BayouBandits.jpg?
3334058: Failed during download of screenshot /upload/userfiles/059/qw65d2dyq6b0ar5pkesv4ml6hh56q0pu/Clipboard01.jpg: Invalid URL '/upload/userfiles/059/qw65d2dyq6b0ar5pkesv4ml6hh56q0pu/Clipboard01.jpg': No
scheme supplied. Perhaps you meant https:///upload/userfiles/059/qw65d2dyq6b0ar5pkesv4ml6hh56q0pu/Clipboard01.jpg?
3334351: Failed during download of screenshot /upload/userfiles/081/23f0hhw4si1nz072o0ropaapwoybshpw/Screenshot_2023-11-15_122929.png: Invalid URL
'/upload/userfiles/081/23f0hhw4si1nz072o0ropaapwoybshpw/Screenshot_2023-11-15_122929.png': No scheme supplied. Perhaps you meant
https:///upload/userfiles/081/23f0hhw4si1nz072o0ropaapwoybshpw/Screenshot_2023-11-15_122929.png?
3336171: Failed during download of screenshot /upload/userfiles/f98/c6hh0mq8uqfh2knfrbe9u39vned5rbkl/RoadRunners.jpg: Invalid URL '/upload/userfiles/f98/c6hh0mq8uqfh2knfrbe9u39vned5rbkl/RoadRunners.jpg': No
scheme supplied. Perhaps you meant https:///upload/userfiles/f98/c6hh0mq8uqfh2knfrbe9u39vned5rbkl/RoadRunners.jpg?
3331423: Failed during download of screenshot /upload/userfiles/649/3l8yg8c2wjmxqmr15qokstewdkdc41so/greyshark.jpg: Invalid URL '/upload/userfiles/649/3l8yg8c2wjmxqmr15qokstewdkdc41so/greyshark.jpg': No scheme
supplied. Perhaps you meant https:///upload/userfiles/649/3l8yg8c2wjmxqmr15qokstewdkdc41so/greyshark.jpg?
3331949: Failed during download of screenshot /upload/userfiles/417/94l8ss8e5up96e4cg2y9eoryll244guo/Screen_240222_203213.jpg: Invalid URL
'/upload/userfiles/417/94l8ss8e5up96e4cg2y9eoryll244guo/Screen_240222_203213.jpg': No scheme supplied. Perhaps you meant https:///upload/userfiles/417/94l8ss8e5up96e4cg2y9eoryll244guo/Screen_240222_203213.jpg?

it just tries the url without www.digitalcombatsimulator.com

with kind regards
toastybank3nobi

**Comment by pearcebergh** [comment]
Thanks for reporting this! It should be fixed in the 1.2.2 release.
